### test without token

POST http://127.0.0.1:3000/api/order
Content-Type: application/json

{
    user_id": 1,
    "book_ids":[1, 2, 3],
    "card_token": "tok"
}

### test with token

POST http://127.0.0.1:3000/api/order
Content-Type: application/json
authorization: BearereyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTU5NjQ4MDAsImlhdCI6MTc1NTk0MjQ2Nywic3ViIjoiMSJ9.tM_lTSJpMUBcrdfsnZsSZkWeSmMY1m7ccZawZHWyJ-o

{
    "user_id": 111,
    "book_ids":[5, 2, 3],
    "card_token": "tiktok"
}

### Create

POST http://127.0.0.1:3000/api/books
Content-Type: application/json

{
    "title": "Learning Perl 6",
    "author": "brian d foy",
    "price": 26.85,
    "stock": 12
}

### Read All

GET http://127.0.0.1:3000/api/books

### Read One

GET http://127.0.0.1:3000/api/books/10

### Update

PUT http://127.0.0.1:3000/api/books/10
Content-Type: application/json

{
    "price": 17.99
}

### Delete

DELETE http://127.0.0.1:3000/api/books/10
